version: "3"
services:
  postgres:
    image: postgres:15.0-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
networks:
  postgres:
    driver: bridge

volumes:
  pg_data: